### ISSUE TITLE
About usage

### ISSUE THREAD

**Issue by cool8jay** [lexrus/LTFinderButtons#11]
Download or `git clone` the buttons in a proper place. Hold on command button and drag each one into your Finder toolbar.

I try this guide first but fail.

After some random action, I find the right steps are:

1. press and hold left mouse button on the icon of app (e.g. CotEditorFinderButton.app) in a Finder window.
2. press and hold command key on keyboard.
3. drag the icon to Finder tool bar.

Any other way is wrong.

**Comment by lexrus** [comment]
I'm using Magic Trackpad 2. I can confirm that I have to press down the command key first.
Could you specify your mouse?

**Comment by cool8jay** [comment]
My mouse is SteelSeries. Also, I try the built-in trackpad, same issue.

By the way, I'm using [Go2Shell](https://itunes.apple.com/cn/app/go2shell/id445770608?l=en&mt=12) to launch terminal at current path.
