### ISSUE TITLE
关于 iTem 2 按钮

### ISSUE THREAD

**Issue by OscarGong** [lexrus/LTFinderButtons#14]
LTFinderButtons/iTerm2FinderButton.app/Contents/Resources/Scripts/main.scpt 应为： 
`var iTerm2 = Application('iTerm2')`
而不是
`var iTerm2 = Application('iTerm')`

**Comment by lexrus** [comment]
Fixed. Thanks.

**Comment by thekoc** [comment]
`var iTerm2 = Application('iTerm2')`
在 iTerm2 已经开启时正常运行，在 iTerm2 没打开时会弹出
> Error: Application can't be found.
错误。

但是
`var iTerm2 = Application('iTerm')`
无论 iTerm2 有没有开启，都可以正常运行…

系统是 macOS Sierra 10.12.5

**Comment by lexrus** [comment]
@thekoc 已修正。

**Comment by OscarGong** [comment]
iTerm2FinderButton.app 在 Jul 10, 2017 Commits 更新后无法运行了…

**Comment by lexrus** [comment]
@OscarGong 刚发现如果窗体不存在 currentWindow() 会抛异常，已经修正，请 pull。
