### ISSUE TITLE
Does not work anymore with 10.14 mojave

### ISSUE THREAD

**Issue by mgcrea** [lexrus/LTFinderButtons#18]
Not sure if it is easily bypass-able but buttons won't work under latest OSX Mojave:

Got this error on click: 

> Not authorized to send apple events to Finder. (-1743)

<img width="488" alt="screenshot 2018-07-17 at 12 29 02" src="https://user-images.githubusercontent.com/108273/42812164-031ce308-89bd-11e8-83e0-e93830eb3e2b.png">

**Comment by mgcrea** [comment]
According to this [stackoverflow answer](https://stackoverflow.com/a/52546696), it looks like re-exporting the .app files would work.

> A workaround is to re-export the Application from the .scpt or .applescript source code. This generates a new .app application, which in my case ran successfully. The initial launch required approval (as well as some subsequent launches), and the application was added as an entry under Settings -> Security & Privacy -> Privacy -> Automation.

**Comment by lexrus** [comment]
@mgcrea It works. Thank you!
I just uploaded 2 new dark buttons. They works in Mojave. Please have a try.

**Comment by dimosz** [comment]
@lexrus VSCodeFinderButton.app cannot work

<img width="419" alt="screen shot 2018-10-08 at 9 42 54 pm" src="https://user-images.githubusercontent.com/16677745/46612646-bbdefa80-cb43-11e8-8fbd-4d2eb0775d15.png">

**Comment by lexrus** [comment]
I just confirmed these buttons still work in the latest macOS Catalina 10.15.5. 😄
