### ISSUE TITLE
可以增加 TextWrangler 支持吗？

### ISSUE THREAD

**Issue by OscarGong** [lexrus/LTFinderButtons#4]
可以增加 TextWrangler 支持吗？

**Comment by lexrus** [comment]
可以呀，不过图标怎么画好呢？还有 BBEdit 也要有吧。

**Comment by OscarGong** [comment]
看这个图标还可以吗……？
https://cl.ly/iB1s

**Comment by lexrus** [comment]
<img width="120" alt="screen shot 2016-11-20 at 7 38 32 pm" src="https://cloud.githubusercontent.com/assets/219689/20462435/f33d9de6-af58-11e6-9713-efd79595f79f.png">
你觉得这样可以吗？顺带画了个 BBEdit 的。

**Comment by OscarGong** [comment]
很棒！
BBEdit 或许逆时针旋转一点会更好……？

**Comment by lexrus** [comment]
<img width="233" alt="screen shot 2016-11-20 at 10 44 19 pm" src="https://cloud.githubusercontent.com/assets/219689/20463649/f6e760b6-af72-11e6-9ee6-b02916ca8b15.png">
恩，斜着好像更生动一些。

**Comment by lexrus** [comment]
发现 Xcode 8 的附加工具里不带 Icon Composer 了，不知道怎么导出图标了。容我找找替代办法，抱歉。

**Comment by lexrus** [comment]
已加上 BBEdit 和 TextWrangler，请 pull 一下。

**Comment by OscarGong** [comment]
图标有问题…
![](http://ww2.sinaimg.cn/large/006tNc79jw1fa1ablhchcj306k04s74t.jpg)

**Comment by lexrus** [comment]
重新拉一下？应该好了。不过 OS X 的图标会缓存，可能需要重启一下。
