### ISSUE TITLE
make all app run in background

### ISSUE THREAD

**Issue by maxming2333** [lexrus/LTFinderButtons#5]
`Info.plist` add this key

```
<key>LSUIElement</key> <true/>
```

or

```
<key>LSBackgroundOnly</key> <true/>
```

And then the application will run silently in the background, not in the dock on the case of a flash.

:)

**Comment by lexrus** [comment]
👍 Cool!
Thank you. Will do after launch.

**Comment by lexrus** [comment]
Done.
