### ISSUE TITLE
Git Pull 以后大部分图标不见了

### ISSUE THREAD

**Issue by OscarGong** [lexrus/LTFinderButtons#8]
![image](https://cloud.githubusercontent.com/assets/7035787/21547512/83dbbfa4-ce21-11e6-8359-5b56a9805eac.png)

大概是这样子
10.12.3 Beta (16D17a)

**Comment by dsmo** [comment]
好像是因为这个commit 9d1289df8ffee0ff5f6da6b4d8edd95301e56b0a 提交的新icon不能正常显示

**Comment by lexrus** [comment]
抱歉，发现 Sketch 导出有 bug，workaround 解决了一下，现在应该能正常显示了，请更新。
另外，Finder 列表模式可能需要 32x32 的图，我暂时没有导出，需要到缩略图模式才能看到。

<img width="563" alt="screen shot 2017-02-07 at 11 15 19 pm" src="https://cloud.githubusercontent.com/assets/219689/22697098/5c42fe38-ed8b-11e6-803d-d2cfc1a4d9d9.png">
