### ISSUE TITLE
iTerm 2 按钮每次点击都会弹出确认窗口

### ISSUE THREAD

**Issue by dsmo** [lexrus/LTFinderButtons#9]
![c471c4bb-2c4a-45c1-90c0-6c4fe558ee51](https://cloud.githubusercontent.com/assets/5320374/22972627/6d41141a-f3b5-11e6-862c-80510192e862.png) 

如图，点击运行后会报错

![1a3f986c-a262-43cd-9977-e6af44e934d6](https://cloud.githubusercontent.com/assets/5320374/22973068/71663262-f3b7-11e6-8d7b-44c0e6e76e58.png)

系统 macOS Sierra 10.12.3 (16D32)

**Comment by lexrus** [comment]
谢谢你，我也发现了。
我已经把 iTerm2 的脚本用 JavaScript 重写了，但是打包方法好像和 AppleScript 的不太一样。明天再测试一下。

**Comment by lexrus** [comment]
已经 push，请更新。

**Comment by dsmo** [comment]
谢谢
